<template>
    <v-speed-dial
      v-model="fab"
      bottom
      fixed
      right
      slide-y-reverse-transition
      open-on-hover
    >
      <template v-slot:activator>
        <v-btn
          v-model="fab"
          color="primary"
          dark
          fab
        >
          <v-icon>mdi-chevron-up</v-icon>
          <v-icon>mdi-chevron-down</v-icon>
        </v-btn>
      </template>
      <v-btn
        fab
        small
        color="blue"
        href="/signout"
        rel="noopener"
      >
        <v-icon>mdi-logout</v-icon>
      </v-btn>
      <v-btn
        fab
        small
        color="red"
        href="/generate_group"
        title="Go to top"
      >
        <v-icon>mdi-account-multiple-plus</v-icon>
      </v-btn>
      <v-btn
        fab
        small
        color="yellow"
        href="/add_schedule"
        rel="noopener"
      >
        <v-icon>mdi-alarm-plus</v-icon>
      </v-btn>
    </v-speed-dial>
</template>
